### ISSUE TITLE
Remove WPF project and turn in to a standalone library

### ISSUE THREAD

**Issue by vincpa** [Muraad/Mime-Detective#3]
Would like to turn this in to a library without the WPF project. What are your thoughts on this?

**Comment by Muraad** [comment]
You mean a separate github project?

**Comment by Muraad** [comment]
As I mentioned in one of the pull requests, this project started as a quick hack. The WPF app probably got some bugs, e.g. no real error handling and so on. Generally im open to a big refactoring of the whole repository.

**Comment by Muraad** [comment]
I will close this
