### ISSUE TITLE
GPL 2 license. Evaluate possibility to switch to MIT/Apache 2.0

### ISSUE THREAD

**Issue by Muraad** [Muraad/Mime-Detective#4]
My "fork" started as a short hack, but since mentioned at StackOverflow it gets some kind of attention.

The original code from https://filetypedetective.codeplex.com/ is GPL2 licensed. That means you have to be open source too if you use this, EXCEPT you use it only internally and don´t distribute it. 

GPL 2 is "problematic" for many use cases i think. You have to be carefull and know what you are doing.
Switching to MIT or Apache 2.0 would make the usage much easier. But we need permission to do this from trailmax (https://www.codeplex.com/site/users/view/trailmax)

@trailmax if you have time, can you comment the issue and tell me your thoughts about this?

**Comment by trailmax** [comment]
Wow! I was not aware that project was forked and used in any sort of environment. Also I was not aware there even was a licence on FileTypeDetective project!

I've changed the original project licence to MIT. I'll be happy if this project takes off and useful to other people!

**Comment by Muraad** [comment]
Hi! 
Yes it seems there is a need for your project. I was forking it as a short hack. But a few weeks ago someone posted this repository as an answer at StackOverflow :) 
Great i will change the license too.
Thank you!

**Comment by trailmax** [comment]
Good stuff! I'll by interested to see if this is getting popular. Ping me a message once you have a nuget package, I'll put a message on codeplex page to redirect people here.

**Comment by vincpa** [comment]
I'm using this in production today as I found the API more accommodating. I also have a few ideas on how to shape the API which I guess we can discuss.

**Comment by Muraad** [comment]
I´m closing this.

**Comment by tiesont** [comment]
[LICENSE](https://github.com/Muraad/Mime-Detective/blob/master/LICENSE) claims an MIT license, but the source code still has a GPL license embedded. Which is correct? If the true license is MIT, someone should update the source; I'll do it for you if you can give me a definitive answer.
